kind: Secret
apiVersion: v1
metadata:
  name: keycloak-db-secret
  namespace: keycloak-operator
  labels:
    app: test-keycloak # Consistent label
    operator.keycloak.org/component: watched-secret
stringData:
  database-name: "keycloak"
  database-password: "postgres"
  database-user: "postgres"
type: Opaque

---

apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  labels:
    app: test-keycloak # Consistent label 
  name: keycloak
  namespace: keycloak-operator
spec:
  additionalOptions:
    - name: hostname-debug
      value: 'true'
    - name: log-level
      value: info
  db:
    passwordSecret:
      key: database-password
      name: keycloak-db-secret
    url: 'jdbc:postgresql://psql-postgresql.postgresql.svc.cluster.local:5432/keycloak'
    usernameSecret:
      key: database-user
      name: keycloak-db-secret
    vendor: postgres
  hostname:
    #hostname: keycloack.apps.cluster-9bvn9.9bvn9.sandbox2300.opentlc.com 
    strict: false
  http:
    httpEnabled: true
  instances: 1
  transaction:
    xaEnabled: false
  proxy:
    mode: edge 
    headers: xforwarded