# Secret for OpenLDAP Admin Password
# Replace 'your-admin-password' with a strong password.
# Base64 encode your password: echo -n 'your-admin-password' | base64
apiVersion: v1
kind: Secret
metadata:
  name: openldap-admin-password
  labels:
    app: test-openldap
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: your-admin-password